"""
    bincoo_ca(;input, outdir, dim, noversamples, niter, chunksize)

Out-of-core Correspondence Analysis (CA) for binary COO data.

Input Arguments
---------
- `input` : Julia Binary file generated by `OnlineNMF.bincoo2bin` function.
- `outdir` : The directory user want to save the result.
- `dim` : The number of dimensions of CA.
- `noversamples` : The number of over-sampling for randomized SVD.
- `niter` : The number of power iterations for randomized SVD.
- `chunksize` : The number of rows reading at once (0 = all rows at once).

Output Arguments
---------
- `F` : Row coordinates (N × dim)
- `G` : Column coordinates (M × dim)
- `σ` : Singular values (dim,)
- `Inertia` : Explained inertia by the dimensions (dim,)
- `TotalInertia` : Total inertia (scalar)
"""
function bincoo_ca(;
    input::AbstractString="",
    outdir::Union{Nothing,AbstractString}=nothing,
    dim::Number=3,
    noversamples::Number=5,
    niter::Number=3,
    chunksize::Number=0,
    rng::AbstractRNG=default_rng(),
    seed::Union{Nothing,Integer}=nothing,
)
    # Initial Setting
    N, M = Int64.(nm(input))
    dim = convert(Int64, dim)
    noversamples = convert(Int64, noversamples)
    niter = convert(Int64, niter)
    chunksize = convert(Int64, chunksize)
    if chunksize <= 0
        chunksize = N
    end
    # Argument Check
    if N < 2
        throw(ArgumentError("Input matrix has only $N row(s). CA requires at least 2 rows."))
    end
    if M < 2
        throw(ArgumentError("Input matrix has only $M column(s). CA requires at least 2 columns."))
    end
    if dim < 1
        throw(ArgumentError("dim must be positive, got $dim"))
    end
    if min(N, M) - 1 < dim
        throw(ArgumentError("dim ($dim) must be <= min(N, M) - 1 = $(min(N, M) - 1)"))
    end

    # Pass 1: Compute row sums, column sums, and total
    println("Pass 1: Computing row sums, column sums, and total...")
    rowsums, colsums, total = compute_sums_bincoo(input, N, M)

    # Compute CA using randomized SVD
    eff_rng = _make_rng(rng, seed)
    out = ca_rsvd_bincoo(input, N, M, dim, noversamples, niter, chunksize, rowsums, colsums, total, eff_rng)

    # Output
    if outdir isa String
        mkpath(outdir)
        output(outdir, out)
    end
    return out
end

# Pass 1: Compute row sums, column sums, total (binary COO)
function compute_sums_bincoo(input, N, M)
    rowsums = zeros(Float64, N)
    colsums = zeros(Float64, M)
    total = 0.0
    open(input) do file
        stream = ZstdDecompressorStream(file)
        tmpN = zeros(UInt32, 1)
        tmpM = zeros(UInt32, 1)
        read!(stream, tmpN)
        read!(stream, tmpM)
        buf = zeros(UInt32, 2)
        while !eof(stream)
            read!(stream, buf)
            row, col = buf[1], buf[2]
            rowsums[row] += 1.0
            colsums[col] += 1.0
            total += 1.0
        end
        close(stream)
    end
    return rowsums, colsums, total
end

# Read one chunk of binary COO data
function read_bincoo_chunk!(stream, N, M, n, chunksize, overflow_buf)
    batch_size = min(chunksize, N - n + 1)
    max_size = (batch_size + 1) * M
    rows = zeros(UInt32, max_size)
    cols = zeros(UInt32, max_size)
    count = 0
    # Overflow buffer
    if length(overflow_buf) > 0
        count += 1
        rows[count] = overflow_buf[1] - n + 1
        cols[count] = overflow_buf[2]
        empty!(overflow_buf)
    end
    while !eof(stream)
        buf = zeros(UInt32, 2)
        read!(stream, buf)
        row, col = buf[1], buf[2]
        if n <= row < n + batch_size
            count += 1
            rows[count] = row - n + 1
            cols[count] = col
        else
            append!(overflow_buf, buf)
            break
        end
    end
    resize!(rows, count)
    resize!(cols, count)
    if count > 0
        X_chunk = sparse(rows, cols, 1, batch_size, M)
    else
        X_chunk = spzeros(batch_size, M)
    end
    return X_chunk, batch_size
end

# Implicit S * Omega (bincoo)
function implicit_S_times_Omega_bincoo(input, N, M, chunksize, rowsums, colsums, total, Omega)
    l = size(Omega, 2)
    Y = zeros(Float64, N, l)
    inv_sqrt_colsums = zeros(Float64, M)
    for j in 1:M
        inv_sqrt_colsums[j] = colsums[j] > 0 ? 1.0 / sqrt(colsums[j] / total) : 0.0
    end
    DcInvSqrt_Omega = Diagonal(inv_sqrt_colsums) * Omega
    cp = colsums ./ total
    cp_DcInvSqrt_Omega = cp' * DcInvSqrt_Omega

    open(input) do file
        stream = ZstdDecompressorStream(file)
        tmpN = zeros(UInt32, 1)
        tmpM = zeros(UInt32, 1)
        read!(stream, tmpN)
        read!(stream, tmpM)
        overflow_buf = UInt32[]
        n = 1
        while n <= N
            X_chunk, batch_size = read_bincoo_chunk!(stream, N, M, n, chunksize, overflow_buf)
            term1 = Matrix(X_chunk * DcInvSqrt_Omega) ./ total
            for i in 1:batch_size
                rp_i = rowsums[n + i - 1] / total
                inv_sqrt_ri = rowsums[n + i - 1] > 0 ? 1.0 / sqrt(rowsums[n + i - 1] / total) : 0.0
                for k in 1:l
                    Y[n + i - 1, k] = inv_sqrt_ri * (term1[i, k] - rp_i * cp_DcInvSqrt_Omega[k])
                end
            end
            n += batch_size
        end
        close(stream)
    end
    return Y
end

# Implicit S' * Q (bincoo)
function implicit_St_times_Q_bincoo(input, N, M, chunksize, rowsums, colsums, total, Q)
    l = size(Q, 2)
    DrInvSqrt_Q = zeros(Float64, N, l)
    for i in 1:N
        inv_sqrt_ri = rowsums[i] > 0 ? 1.0 / sqrt(rowsums[i] / total) : 0.0
        for k in 1:l
            DrInvSqrt_Q[i, k] = inv_sqrt_ri * Q[i, k]
        end
    end
    rp = rowsums ./ total
    rp_DrInvSqrt_Q = rp' * DrInvSqrt_Q

    AtQ = zeros(Float64, M, l)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        tmpN = zeros(UInt32, 1)
        tmpM = zeros(UInt32, 1)
        read!(stream, tmpN)
        read!(stream, tmpM)
        overflow_buf = UInt32[]
        n = 1
        while n <= N
            X_chunk, batch_size = read_bincoo_chunk!(stream, N, M, n, chunksize, overflow_buf)
            Q_chunk = @view DrInvSqrt_Q[n:n+batch_size-1, :]
            AtQ .+= Matrix(X_chunk' * Q_chunk)
            n += batch_size
        end
        close(stream)
    end
    result = zeros(Float64, M, l)
    cp = colsums ./ total
    for j in 1:M
        inv_sqrt_cj = colsums[j] > 0 ? 1.0 / sqrt(colsums[j] / total) : 0.0
        for k in 1:l
            result[j, k] = inv_sqrt_cj * (AtQ[j, k] / total - cp[j] * rp_DrInvSqrt_Q[k])
        end
    end
    return result
end

# Randomized SVD for CA (bincoo)
function ca_rsvd_bincoo(input, N, M, dim, noversamples, niter, chunksize, rowsums, colsums, total, rng::AbstractRNG=default_rng())
    l = dim + noversamples
    @assert 0 < dim <= l <= min(N, M)

    println("Random Projection: Y = S * Omega")
    Omega = rand(rng, Float64, M, l)
    Y = implicit_S_times_Omega_bincoo(input, N, M, chunksize, rowsums, colsums, total, Omega)

    println("QR factorization: Q = qr(Y)")
    Q = Array(qr!(Y).Q)

    for i in 1:niter
        println("Subspace iteration $i / $niter")
        G = implicit_St_times_Q_bincoo(input, N, M, chunksize, rowsums, colsums, total, Q)
        G = Array(qr!(G).Q)
        Y = implicit_S_times_Omega_bincoo(input, N, M, chunksize, rowsums, colsums, total, G)
        Q = Array(qr!(Y).Q)
    end

    println("Computing small matrix: B = Q' S")
    StQ = implicit_St_times_Q_bincoo(input, N, M, chunksize, rowsums, colsums, total, Q)
    B = StQ'

    println("SVD of small matrix: svd(B)")
    W, sigma, Vt = svd(B)
    U_svd = Q * W

    sigma_dim = sigma[1:dim]
    U_dim = U_svd[:, 1:dim]
    V_dim = Vt[:, 1:dim]

    total_inertia, rowdist2, coldist2 =
        compute_inertias_bincoo(input, N, M, rowsums, colsums, total)

    return _build_result(U_dim, V_dim, sigma_dim,
                         rowsums, colsums, total,
                         total_inertia, rowdist2, coldist2)
end

# Compute total inertia + per-row/col S_ij^2 sums (bincoo). Same algebra as
# the sparse version, with x ≡ 1 for every nonzero cell.
function compute_inertias_bincoo(input, N, M, rowsums, colsums, total)
    chi2_nonzero          = 0.0
    sum_e_nonzero         = 0.0
    rowdist2              = zeros(Float64, N)
    coldist2              = zeros(Float64, M)
    rowexp_nonzero        = zeros(Float64, N)
    colexp_nonzero        = zeros(Float64, M)

    open(input) do file
        stream = ZstdDecompressorStream(file)
        tmpN = zeros(UInt32, 1)
        tmpM = zeros(UInt32, 1)
        read!(stream, tmpN)
        read!(stream, tmpM)
        buf = zeros(UInt32, 2)
        while !eof(stream)
            read!(stream, buf)
            row, col = buf[1], buf[2]
            e = rowsums[row] * colsums[col] / total
            if e > 0
                chi2_cell             = (1.0 - e)^2 / e
                chi2_nonzero         += chi2_cell
                sum_e_nonzero        += e
                rowdist2[row]        += chi2_cell
                coldist2[col]        += chi2_cell
                rowexp_nonzero[row]  += e
                colexp_nonzero[col]  += e
            end
        end
        close(stream)
    end

    @inbounds for i in 1:N
        rowdist2[i] += rowsums[i] - rowexp_nonzero[i]
    end
    @inbounds for j in 1:M
        coldist2[j] += colsums[j] - colexp_nonzero[j]
    end

    total_chi2 = chi2_nonzero + (total - sum_e_nonzero)

    rowdist2 ./= total
    coldist2 ./= total
    return total_chi2 / total, rowdist2, coldist2
end
