"""
    ca(;input, outdir, dim, noversamples, niter, chunksize)

Out-of-core Correspondence Analysis (CA) for dense data.

Uses Halko-style randomized SVD on the implicit standardized residual matrix
S = D_r^{-1/2} (P - r_p c_p') D_c^{-1/2}, where P = X/n.

The matrix S is never explicitly formed. Instead, matrix-vector products
S*v and S'*u are computed by streaming through the data.

Input Arguments
---------
- `input` : Julia Binary file generated by `OnlinePCA.csv2bin` function.
- `outdir` : The directory user want to save the result.
- `dim` : The number of dimensions of CA.
- `noversamples` : The number of over-sampling for randomized SVD.
- `niter` : The number of power iterations for randomized SVD.
- `chunksize` : The number of rows reading at once (0 = all rows at once).

Output Arguments
---------
- `F` : Row coordinates (N × dim)
- `G` : Column coordinates (M × dim)
- `σ` : Singular values (dim,)
- `Inertia` : Explained inertia by the dimensions (dim,)
- `TotalInertia` : Total inertia (scalar)
"""
function ca(;
    input::AbstractString="",
    outdir::Union{Nothing,AbstractString}=nothing,
    dim::Number=3,
    noversamples::Number=5,
    niter::Number=3,
    chunksize::Number=0,
)
    # Initial Setting
    N, M = Int64.(nm(input))
    dim = convert(Int64, dim)
    noversamples = convert(Int64, noversamples)
    niter = convert(Int64, niter)
    chunksize = convert(Int64, chunksize)
    if chunksize <= 0
        chunksize = N
    end
    # Argument Check
    if N < 2
        throw(ArgumentError("Input matrix has only $N row(s). CA requires at least 2 rows."))
    end
    if M < 2
        throw(ArgumentError("Input matrix has only $M column(s). CA requires at least 2 columns."))
    end
    if dim < 1
        throw(ArgumentError("dim must be positive, got $dim"))
    end
    if min(N, M) - 1 < dim
        throw(ArgumentError("dim ($dim) must be <= min(N, M) - 1 = $(min(N, M) - 1)"))
    end

    # Pass 1: Compute row sums, column sums, and total
    println("Pass 1: Computing row sums, column sums, and total...")
    rowsums, colsums, total = compute_sums_dense(input, N, M, chunksize)

    # Compute CA using randomized SVD
    out = ca_rsvd_dense(input, N, M, dim, noversamples, niter, chunksize, rowsums, colsums, total)

    # Output
    if outdir isa String
        mkpath(outdir)
        output(outdir, out)
    end
    return out
end

# Pass 1: Compute row sums, column sums, total (dense)
function compute_sums_dense(input, N, M, chunksize)
    rowsums = zeros(Float64, N)
    colsums = zeros(Float64, M)
    total = 0.0
    tmpN = zeros(UInt32, 1)
    tmpM = zeros(UInt32, 1)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        read!(stream, tmpN)
        read!(stream, tmpM)
        n = 1
        while n <= N
            batch_size = min(chunksize, N - n + 1)
            buffer = zeros(UInt32, batch_size * M)
            read!(stream, buffer)
            X_chunk = permutedims(reshape(buffer, M, batch_size))
            for i in 1:batch_size
                for j in 1:M
                    v = Float64(X_chunk[i, j])
                    rowsums[n + i - 1] += v
                    colsums[j] += v
                    total += v
                end
            end
            n += batch_size
        end
        close(stream)
    end
    return rowsums, colsums, total
end

# Implicit S * Ω: compute D_r^{-1/2} (X/(n) - r_p c_p') D_c^{-1/2} * Ω by streaming
# = D_r^{-1/2} [ X * (D_c^{-1/2} Ω) / n  -  r_p * (c_p' D_c^{-1/2} Ω) ]
function implicit_S_times_Omega_dense(input, N, M, chunksize, rowsums, colsums, total, Omega)
    l = size(Omega, 2)
    Y = zeros(Float64, N, l)
    # Precompute: D_c^{-1/2} * Omega (M × l)
    inv_sqrt_colsums = zeros(Float64, M)
    for j in 1:M
        inv_sqrt_colsums[j] = colsums[j] > 0 ? 1.0 / sqrt(colsums[j] / total) : 0.0
    end
    DcInvSqrt_Omega = Diagonal(inv_sqrt_colsums) * Omega  # M × l
    # Precompute: c_p' * D_c^{-1/2} * Omega (1 × l)
    cp = colsums ./ total  # M
    cp_DcInvSqrt_Omega = cp' * DcInvSqrt_Omega  # 1 × l

    tmpN = zeros(UInt32, 1)
    tmpM = zeros(UInt32, 1)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        read!(stream, tmpN)
        read!(stream, tmpM)
        n = 1
        while n <= N
            batch_size = min(chunksize, N - n + 1)
            buffer = zeros(UInt32, batch_size * M)
            read!(stream, buffer)
            X_chunk = Float64.(permutedims(reshape(buffer, M, batch_size)))  # batch_size × M
            # X_chunk * DcInvSqrt_Omega / total
            term1 = X_chunk * DcInvSqrt_Omega ./ total  # batch_size × l
            # r_p[n:n+bs-1] * (c_p' D_c^{-1/2} Omega)
            for i in 1:batch_size
                rp_i = rowsums[n + i - 1] / total
                for k in 1:l
                    Y[n + i - 1, k] = (term1[i, k] - rp_i * cp_DcInvSqrt_Omega[k])
                end
            end
            n += batch_size
        end
        close(stream)
    end
    # Multiply by D_r^{-1/2}
    for i in 1:N
        inv_sqrt_ri = rowsums[i] > 0 ? 1.0 / sqrt(rowsums[i] / total) : 0.0
        for k in 1:l
            Y[i, k] *= inv_sqrt_ri
        end
    end
    return Y
end

# Implicit S' * Q: compute D_c^{-1/2} (X'/(n) - c_p r_p') D_r^{-1/2} * Q by streaming
# = D_c^{-1/2} [ X' * (D_r^{-1/2} Q) / n  -  c_p * (r_p' D_r^{-1/2} Q) ]
function implicit_St_times_Q_dense(input, N, M, chunksize, rowsums, colsums, total, Q)
    l = size(Q, 2)
    # Precompute: D_r^{-1/2} * Q (N × l)
    DrInvSqrt_Q = zeros(Float64, N, l)
    for i in 1:N
        inv_sqrt_ri = rowsums[i] > 0 ? 1.0 / sqrt(rowsums[i] / total) : 0.0
        for k in 1:l
            DrInvSqrt_Q[i, k] = inv_sqrt_ri * Q[i, k]
        end
    end
    # Precompute: r_p' * D_r^{-1/2} * Q (1 × l)
    rp = rowsums ./ total  # N
    rp_DrInvSqrt_Q = rp' * DrInvSqrt_Q  # 1 × l

    # Accumulate X' * DrInvSqrt_Q by streaming
    AtQ = zeros(Float64, M, l)
    tmpN = zeros(UInt32, 1)
    tmpM = zeros(UInt32, 1)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        read!(stream, tmpN)
        read!(stream, tmpM)
        n = 1
        while n <= N
            batch_size = min(chunksize, N - n + 1)
            buffer = zeros(UInt32, batch_size * M)
            read!(stream, buffer)
            X_chunk = Float64.(permutedims(reshape(buffer, M, batch_size)))  # batch_size × M
            Q_chunk = @view DrInvSqrt_Q[n:n+batch_size-1, :]  # batch_size × l
            AtQ .+= X_chunk' * Q_chunk  # M × l
            n += batch_size
        end
        close(stream)
    end
    # Result = D_c^{-1/2} [ AtQ / n  -  c_p * rp_DrInvSqrt_Q ]
    result = zeros(Float64, M, l)
    cp = colsums ./ total
    for j in 1:M
        inv_sqrt_cj = colsums[j] > 0 ? 1.0 / sqrt(colsums[j] / total) : 0.0
        for k in 1:l
            result[j, k] = inv_sqrt_cj * (AtQ[j, k] / total - cp[j] * rp_DrInvSqrt_Q[k])
        end
    end
    return result
end

# Randomized SVD for CA (dense)
function ca_rsvd_dense(input, N, M, dim, noversamples, niter, chunksize, rowsums, colsums, total)
    l = dim + noversamples
    @assert 0 < dim <= l <= min(N, M)

    # Step 1: Random projection Y = S * Omega
    println("Random Projection: Y = S * Omega")
    Omega = rand(Float64, M, l)
    Y = implicit_S_times_Omega_dense(input, N, M, chunksize, rowsums, colsums, total, Omega)

    # Step 2: QR factorization
    println("QR factorization: Q = qr(Y)")
    Q = Array(qr!(Y).Q)

    # Step 3: Power iterations
    for i in 1:niter
        println("Subspace iteration $i / $niter")
        # G = S' * Q
        G = implicit_St_times_Q_dense(input, N, M, chunksize, rowsums, colsums, total, Q)
        G = Array(qr!(G).Q)
        # Y = S * G
        Y = implicit_S_times_Omega_dense(input, N, M, chunksize, rowsums, colsums, total, G)
        Q = Array(qr!(Y).Q)
    end

    # Step 4: B = Q' * S * I  (compute via S' * Q then transpose)
    # Actually B = Q' A_implicit, compute as: B[k, j] = Q[:, k]' * S[:, j]
    # More efficient: B = (S' Q)' , but we already have the function
    println("Computing small matrix: B = Q' S")
    StQ = implicit_St_times_Q_dense(input, N, M, chunksize, rowsums, colsums, total, Q)
    B = StQ'  # l × M

    # Step 5: SVD of small matrix
    println("SVD of small matrix: svd(B)")
    W, sigma, Vt = svd(B)
    # U_svd = Q * W
    U_svd = Q * W

    # Extract top dim components
    sigma_dim = sigma[1:dim]
    U_dim = U_svd[:, 1:dim]
    V_dim = Vt[:, 1:dim]

    # Compute CA coordinates
    # Row coordinates: F = D_r^{-1/2} * U_dim * Diag(sigma_dim)
    # But U_dim is already in the space of D_r^{-1/2} * ... so we just scale
    # F_i = sigma_k * U_dim[i, k]  (standard coordinates * sigma = principal coordinates)
    F = zeros(Float64, N, dim)
    G = zeros(Float64, M, dim)
    for k in 1:dim
        for i in 1:N
            F[i, k] = sigma_dim[k] * U_dim[i, k]
        end
        for j in 1:M
            G[j, k] = sigma_dim[k] * V_dim[j, k]
        end
    end

    # Inertia (explained by each dimension)
    total_inertia = compute_total_inertia_dense(input, N, M, chunksize, rowsums, colsums, total)
    inertia = sigma_dim .^ 2

    return (F, G, sigma_dim, inertia, total_inertia)
end

# Compute total inertia = sum of all (S_ij)^2 = chi-squared / n
# = sum_ij (x_ij / n - r_i * c_j / n^2)^2 / (r_i/n * c_j/n)
# = sum_ij (x_ij - r_i * c_j / n)^2 / (r_i * c_j / n)  * (1/n)
function compute_total_inertia_dense(input, N, M, chunksize, rowsums, colsums, total)
    inertia = 0.0
    tmpN = zeros(UInt32, 1)
    tmpM = zeros(UInt32, 1)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        read!(stream, tmpN)
        read!(stream, tmpM)
        n = 1
        while n <= N
            batch_size = min(chunksize, N - n + 1)
            buffer = zeros(UInt32, batch_size * M)
            read!(stream, buffer)
            X_chunk = Float64.(permutedims(reshape(buffer, M, batch_size)))
            for i in 1:batch_size
                ri = rowsums[n + i - 1]
                for j in 1:M
                    cj = colsums[j]
                    expected = ri * cj / total
                    if expected > 0
                        inertia += (Float64(X_chunk[i, j]) - expected)^2 / expected
                    end
                end
            end
            n += batch_size
        end
        close(stream)
    end
    return inertia / total
end
