"""
    ca(;input, outdir, dim, noversamples, niter, chunksize)

Out-of-core Correspondence Analysis (CA) for dense data.

Uses Halko-style randomized SVD on the implicit standardized residual matrix
S = D_r^{-1/2} (P - r_p c_p') D_c^{-1/2}, where P = X/n.

The matrix S is never explicitly formed. Instead, matrix-vector products
S*v and S'*u are computed by streaming through the data.

Input Arguments
---------
- `input` : Julia Binary file generated by `OnlinePCA.csv2bin` function.
- `outdir` : The directory user want to save the result.
- `dim` : The number of dimensions of CA.
- `noversamples` : The number of over-sampling for randomized SVD.
- `niter` : The number of power iterations for randomized SVD.
- `chunksize` : The number of rows reading at once (0 = all rows at once).

Output Arguments
---------
- `F` : Row coordinates (N × dim)
- `G` : Column coordinates (M × dim)
- `σ` : Singular values (dim,)
- `Inertia` : Explained inertia by the dimensions (dim,)
- `TotalInertia` : Total inertia (scalar)
"""
function ca(;
    input::AbstractString="",
    outdir::Union{Nothing,AbstractString}=nothing,
    dim::Number=3,
    noversamples::Number=5,
    niter::Number=3,
    chunksize::Number=0,
    rng::AbstractRNG=default_rng(),
    seed::Union{Nothing,Integer}=nothing,
    T::Type=Float64,
)
    # Initial Setting
    N, M = Int64.(nm(input))
    dim = convert(Int64, dim)
    noversamples = convert(Int64, noversamples)
    niter = convert(Int64, niter)
    chunksize = convert(Int64, chunksize)
    if chunksize <= 0
        chunksize = N
    end
    # Argument Check
    if N < 2
        throw(ArgumentError("Input matrix has only $N row(s). CA requires at least 2 rows."))
    end
    if M < 2
        throw(ArgumentError("Input matrix has only $M column(s). CA requires at least 2 columns."))
    end
    if dim < 1
        throw(ArgumentError("dim must be positive, got $dim"))
    end
    if min(N, M) - 1 < dim
        throw(ArgumentError("dim ($dim) must be <= min(N, M) - 1 = $(min(N, M) - 1)"))
    end

    # Pass 1: Compute row sums, column sums, and total
    println("Pass 1: Computing row sums, column sums, and total...")
    rowsums, colsums, total = compute_sums_dense(input, N, M, chunksize)

    # Compute CA using randomized SVD
    eff_rng = _make_rng(rng, seed)
    out = ca_rsvd_dense(input, N, M, dim, noversamples, niter, chunksize, rowsums, colsums, total, eff_rng, T)

    # Output
    if outdir isa String
        mkpath(outdir)
        output(outdir, out)
    end
    return out
end

# Pass 1: Compute row sums, column sums, total (dense)
function compute_sums_dense(input, N, M, chunksize)
    rowsums = zeros(Float64, N)
    colsums = zeros(Float64, M)
    total = 0.0
    tmpN = zeros(UInt32, 1)
    tmpM = zeros(UInt32, 1)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        read!(stream, tmpN)
        read!(stream, tmpM)
        n = 1
        while n <= N
            batch_size = min(chunksize, N - n + 1)
            buffer = zeros(UInt32, batch_size * M)
            read!(stream, buffer)
            X_chunk = permutedims(reshape(buffer, M, batch_size))
            for i in 1:batch_size
                for j in 1:M
                    v = Float64(X_chunk[i, j])
                    rowsums[n + i - 1] += v
                    colsums[j] += v
                    total += v
                end
            end
            n += batch_size
        end
        close(stream)
    end
    return rowsums, colsums, total
end

# Implicit S * Ω: compute D_r^{-1/2} (X/(n) - r_p c_p') D_c^{-1/2} * Ω by streaming
# = D_r^{-1/2} [ X * (D_c^{-1/2} Ω) / n  -  r_p * (c_p' D_c^{-1/2} Ω) ]
function implicit_S_times_Omega_dense(input, N, M, chunksize, rowsums, colsums, total, Omega)
    T = eltype(Omega)
    l = size(Omega, 2)
    Y = zeros(T, N, l)
    inv_sqrt_colsums = _inv_sqrt_mass(T, colsums, total)
    DcInvSqrt_Omega  = Diagonal(inv_sqrt_colsums) * Omega          # M × l
    cp                 = T.(colsums ./ total)                       # M
    cp_DcInvSqrt_Omega = cp' * DcInvSqrt_Omega                      # 1 × l

    tmpN = zeros(UInt32, 1)
    tmpM = zeros(UInt32, 1)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        read!(stream, tmpN)
        read!(stream, tmpM)
        n = 1
        while n <= N
            batch_size = min(chunksize, N - n + 1)
            buffer = zeros(UInt32, batch_size * M)
            read!(stream, buffer)
            X_chunk = T.(permutedims(reshape(buffer, M, batch_size)))   # batch_size × M
            term1   = X_chunk * DcInvSqrt_Omega ./ T(total)             # batch_size × l
            for i in 1:batch_size
                rp_i = T(rowsums[n + i - 1] / total)
                for k in 1:l
                    Y[n + i - 1, k] = term1[i, k] - rp_i * cp_DcInvSqrt_Omega[k]
                end
            end
            n += batch_size
        end
        close(stream)
    end
    inv_sqrt_rowsums = _inv_sqrt_mass(T, rowsums, total)
    for i in 1:N
        s = inv_sqrt_rowsums[i]
        for k in 1:l
            Y[i, k] *= s
        end
    end
    return Y
end

# Implicit S' * Q: compute D_c^{-1/2} (X'/(n) - c_p r_p') D_r^{-1/2} * Q by streaming
# = D_c^{-1/2} [ X' * (D_r^{-1/2} Q) / n  -  c_p * (r_p' D_r^{-1/2} Q) ]
function implicit_St_times_Q_dense(input, N, M, chunksize, rowsums, colsums, total, Q)
    T = eltype(Q)
    l = size(Q, 2)
    inv_sqrt_rowsums = _inv_sqrt_mass(T, rowsums, total)
    DrInvSqrt_Q = zeros(T, N, l)
    for i in 1:N
        s = inv_sqrt_rowsums[i]
        for k in 1:l
            DrInvSqrt_Q[i, k] = s * Q[i, k]
        end
    end
    rp             = T.(rowsums ./ total)
    rp_DrInvSqrt_Q = rp' * DrInvSqrt_Q

    AtQ = zeros(T, M, l)
    tmpN = zeros(UInt32, 1)
    tmpM = zeros(UInt32, 1)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        read!(stream, tmpN)
        read!(stream, tmpM)
        n = 1
        while n <= N
            batch_size = min(chunksize, N - n + 1)
            buffer = zeros(UInt32, batch_size * M)
            read!(stream, buffer)
            X_chunk = T.(permutedims(reshape(buffer, M, batch_size)))
            Q_chunk = @view DrInvSqrt_Q[n:n+batch_size-1, :]
            AtQ .+= X_chunk' * Q_chunk
            n += batch_size
        end
        close(stream)
    end
    inv_sqrt_colsums = _inv_sqrt_mass(T, colsums, total)
    cp = T.(colsums ./ total)
    result = zeros(T, M, l)
    for j in 1:M
        s = inv_sqrt_colsums[j]
        for k in 1:l
            result[j, k] = s * (AtQ[j, k] / T(total) - cp[j] * rp_DrInvSqrt_Q[k])
        end
    end
    return result
end

# Randomized SVD for CA (dense)
function ca_rsvd_dense(input, N, M, dim, noversamples, niter, chunksize, rowsums, colsums, total,
                       rng::AbstractRNG=default_rng(), T::Type=Float64)
    l = dim + noversamples
    @assert 0 < dim <= l <= min(N, M)

    # Step 1: Random projection Y = S * Omega
    println("Random Projection: Y = S * Omega")
    Omega = rand(rng, T, M, l)
    Y = implicit_S_times_Omega_dense(input, N, M, chunksize, rowsums, colsums, total, Omega)

    # Step 2: QR factorization
    println("QR factorization: Q = qr(Y)")
    Q = Array(qr!(Y).Q)

    # Step 3: Power iterations
    for i in 1:niter
        println("Subspace iteration $i / $niter")
        # G = S' * Q
        G = implicit_St_times_Q_dense(input, N, M, chunksize, rowsums, colsums, total, Q)
        G = Array(qr!(G).Q)
        # Y = S * G
        Y = implicit_S_times_Omega_dense(input, N, M, chunksize, rowsums, colsums, total, G)
        Q = Array(qr!(Y).Q)
    end

    # Step 4: B = Q' * S * I  (compute via S' * Q then transpose)
    # Actually B = Q' A_implicit, compute as: B[k, j] = Q[:, k]' * S[:, j]
    # More efficient: B = (S' Q)' , but we already have the function
    println("Computing small matrix: B = Q' S")
    StQ = implicit_St_times_Q_dense(input, N, M, chunksize, rowsums, colsums, total, Q)
    B = StQ'  # l × M

    # Step 5: SVD of small matrix
    println("SVD of small matrix: svd(B)")
    W, sigma, Vt = svd(B)
    # U_svd = Q * W
    U_svd = Q * W

    # Extract top dim components
    sigma_dim = sigma[1:dim]
    U_dim = U_svd[:, 1:dim]
    V_dim = Vt[:, 1:dim]

    # Marginal squared S entries are computed in the same OOC pass as total
    # inertia; they are needed for cos² and would otherwise require an extra
    # pass over the data.
    total_inertia, rowdist2, coldist2 =
        compute_inertias_dense(input, N, M, chunksize, rowsums, colsums, total)

    return _build_result(U_dim, V_dim, sigma_dim,
                         rowsums, colsums, total,
                         total_inertia, rowdist2, coldist2)
end

# Compute total inertia = Σ S_ij^2 (chi-squared / n) along with the per-row
# and per-column sums of S_ij^2 (needed for cos²).
function compute_inertias_dense(input, N, M, chunksize, rowsums, colsums, total)
    rowdist2 = zeros(Float64, N)
    coldist2 = zeros(Float64, M)
    inertia  = 0.0
    tmpN = zeros(UInt32, 1)
    tmpM = zeros(UInt32, 1)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        read!(stream, tmpN)
        read!(stream, tmpM)
        n = 1
        while n <= N
            batch_size = min(chunksize, N - n + 1)
            buffer = zeros(UInt32, batch_size * M)
            read!(stream, buffer)
            X_chunk = Float64.(permutedims(reshape(buffer, M, batch_size)))
            for i in 1:batch_size
                global_i = n + i - 1
                ri = rowsums[global_i]
                for j in 1:M
                    cj = colsums[j]
                    expected = ri * cj / total
                    if expected > 0
                        s2 = (Float64(X_chunk[i, j]) - expected)^2 / expected
                        rowdist2[global_i] += s2
                        coldist2[j]        += s2
                        inertia            += s2
                    end
                end
            end
            n += batch_size
        end
        close(stream)
    end
    # Each S_ij^2 was accumulated as chi-square cell value; divide by total once.
    rowdist2 ./= total
    coldist2 ./= total
    return inertia / total, rowdist2, coldist2
end
