"""
    sparse_ca(;input, outdir, dim, noversamples, niter, chunksize)

Out-of-core Correspondence Analysis (CA) for sparse data (MatrixMarket format).

Input Arguments
---------
- `input` : Julia Binary file generated by `OnlinePCA.mm2bin` function.
- `outdir` : The directory user want to save the result.
- `dim` : The number of dimensions of CA.
- `noversamples` : The number of over-sampling for randomized SVD.
- `niter` : The number of power iterations for randomized SVD.
- `chunksize` : The number of rows reading at once (0 = all rows at once).

Output Arguments
---------
- `F` : Row coordinates (N × dim)
- `G` : Column coordinates (M × dim)
- `σ` : Singular values (dim,)
- `Inertia` : Explained inertia by the dimensions (dim,)
- `TotalInertia` : Total inertia (scalar)
"""
function sparse_ca(;
    input::AbstractString="",
    outdir::Union{Nothing,AbstractString}=nothing,
    dim::Number=3,
    noversamples::Number=5,
    niter::Number=3,
    chunksize::Number=0,
)
    # Initial Setting
    N, M = Int64.(nm(input))
    dim = convert(Int64, dim)
    noversamples = convert(Int64, noversamples)
    niter = convert(Int64, niter)
    chunksize = convert(Int64, chunksize)
    if chunksize <= 0
        chunksize = N
    end
    # Argument Check
    if N < 2
        throw(ArgumentError("Input matrix has only $N row(s). CA requires at least 2 rows."))
    end
    if M < 2
        throw(ArgumentError("Input matrix has only $M column(s). CA requires at least 2 columns."))
    end
    if dim < 1
        throw(ArgumentError("dim must be positive, got $dim"))
    end
    if min(N, M) - 1 < dim
        throw(ArgumentError("dim ($dim) must be <= min(N, M) - 1 = $(min(N, M) - 1)"))
    end

    # Pass 1: Compute row sums, column sums, and total
    println("Pass 1: Computing row sums, column sums, and total...")
    rowsums, colsums, total = compute_sums_sparse(input, N, M)

    # Compute CA using randomized SVD
    out = ca_rsvd_sparse(input, N, M, dim, noversamples, niter, chunksize, rowsums, colsums, total)

    # Output
    if outdir isa String
        mkpath(outdir)
        output(outdir, out)
    end
    return out
end

# Pass 1: Compute row sums, column sums, total (sparse COO)
function compute_sums_sparse(input, N, M)
    rowsums = zeros(Float64, N)
    colsums = zeros(Float64, M)
    total = 0.0
    open(input) do file
        stream = ZstdDecompressorStream(file)
        tmpN = zeros(UInt32, 1)
        tmpM = zeros(UInt32, 1)
        read!(stream, tmpN)
        read!(stream, tmpM)
        buf = zeros(UInt32, 3)
        while !eof(stream)
            read!(stream, buf)
            row, col, val = buf[1], buf[2], buf[3]
            rowsums[row] += Float64(val)
            colsums[col] += Float64(val)
            total += Float64(val)
        end
        close(stream)
    end
    return rowsums, colsums, total
end

# Read one chunk of sparse data, returning a SparseMatrixCSC
function read_sparse_chunk!(stream, N, M, n, chunksize, overflow_buf)
    batch_size = min(chunksize, N - n + 1)
    max_size = (batch_size + 1) * M
    rows = zeros(UInt32, max_size)
    cols = zeros(UInt32, max_size)
    vals = zeros(UInt32, max_size)
    count = 0
    # Overflow buffer
    if length(overflow_buf) > 0
        count += 1
        rows[count] = overflow_buf[1] - n + 1
        cols[count] = overflow_buf[2]
        vals[count] = overflow_buf[3]
        empty!(overflow_buf)
    end
    while !eof(stream)
        buf = zeros(UInt32, 3)
        read!(stream, buf)
        row, col, val = buf[1], buf[2], buf[3]
        if n <= row < n + batch_size
            count += 1
            rows[count] = row - n + 1
            cols[count] = col
            vals[count] = val
        else
            append!(overflow_buf, buf)
            break
        end
    end
    resize!(rows, count)
    resize!(cols, count)
    resize!(vals, count)
    if count > 0
        X_chunk = sparse(rows, cols, vals, batch_size, M)
    else
        X_chunk = spzeros(batch_size, M)
    end
    return X_chunk, batch_size
end

# Implicit S * Omega (sparse)
function implicit_S_times_Omega_sparse(input, N, M, chunksize, rowsums, colsums, total, Omega)
    l = size(Omega, 2)
    Y = zeros(Float64, N, l)
    inv_sqrt_colsums = zeros(Float64, M)
    for j in 1:M
        inv_sqrt_colsums[j] = colsums[j] > 0 ? 1.0 / sqrt(colsums[j] / total) : 0.0
    end
    DcInvSqrt_Omega = Diagonal(inv_sqrt_colsums) * Omega
    cp = colsums ./ total
    cp_DcInvSqrt_Omega = cp' * DcInvSqrt_Omega  # 1 × l

    open(input) do file
        stream = ZstdDecompressorStream(file)
        tmpN = zeros(UInt32, 1)
        tmpM = zeros(UInt32, 1)
        read!(stream, tmpN)
        read!(stream, tmpM)
        overflow_buf = UInt32[]
        n = 1
        while n <= N
            X_chunk, batch_size = read_sparse_chunk!(stream, N, M, n, chunksize, overflow_buf)
            # X_chunk * DcInvSqrt_Omega / total
            term1 = Matrix(X_chunk * DcInvSqrt_Omega) ./ total
            for i in 1:batch_size
                rp_i = rowsums[n + i - 1] / total
                inv_sqrt_ri = rowsums[n + i - 1] > 0 ? 1.0 / sqrt(rowsums[n + i - 1] / total) : 0.0
                for k in 1:l
                    Y[n + i - 1, k] = inv_sqrt_ri * (term1[i, k] - rp_i * cp_DcInvSqrt_Omega[k])
                end
            end
            n += batch_size
        end
        close(stream)
    end
    return Y
end

# Implicit S' * Q (sparse)
function implicit_St_times_Q_sparse(input, N, M, chunksize, rowsums, colsums, total, Q)
    l = size(Q, 2)
    DrInvSqrt_Q = zeros(Float64, N, l)
    for i in 1:N
        inv_sqrt_ri = rowsums[i] > 0 ? 1.0 / sqrt(rowsums[i] / total) : 0.0
        for k in 1:l
            DrInvSqrt_Q[i, k] = inv_sqrt_ri * Q[i, k]
        end
    end
    rp = rowsums ./ total
    rp_DrInvSqrt_Q = rp' * DrInvSqrt_Q  # 1 × l

    AtQ = zeros(Float64, M, l)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        tmpN = zeros(UInt32, 1)
        tmpM = zeros(UInt32, 1)
        read!(stream, tmpN)
        read!(stream, tmpM)
        overflow_buf = UInt32[]
        n = 1
        while n <= N
            X_chunk, batch_size = read_sparse_chunk!(stream, N, M, n, chunksize, overflow_buf)
            Q_chunk = @view DrInvSqrt_Q[n:n+batch_size-1, :]
            AtQ .+= Matrix(X_chunk' * Q_chunk)
            n += batch_size
        end
        close(stream)
    end
    result = zeros(Float64, M, l)
    cp = colsums ./ total
    for j in 1:M
        inv_sqrt_cj = colsums[j] > 0 ? 1.0 / sqrt(colsums[j] / total) : 0.0
        for k in 1:l
            result[j, k] = inv_sqrt_cj * (AtQ[j, k] / total - cp[j] * rp_DrInvSqrt_Q[k])
        end
    end
    return result
end

# Randomized SVD for CA (sparse)
function ca_rsvd_sparse(input, N, M, dim, noversamples, niter, chunksize, rowsums, colsums, total)
    l = dim + noversamples
    @assert 0 < dim <= l <= min(N, M)

    println("Random Projection: Y = S * Omega")
    Omega = rand(Float64, M, l)
    Y = implicit_S_times_Omega_sparse(input, N, M, chunksize, rowsums, colsums, total, Omega)

    println("QR factorization: Q = qr(Y)")
    Q = Array(qr!(Y).Q)

    for i in 1:niter
        println("Subspace iteration $i / $niter")
        G = implicit_St_times_Q_sparse(input, N, M, chunksize, rowsums, colsums, total, Q)
        G = Array(qr!(G).Q)
        Y = implicit_S_times_Omega_sparse(input, N, M, chunksize, rowsums, colsums, total, G)
        Q = Array(qr!(Y).Q)
    end

    println("Computing small matrix: B = Q' S")
    StQ = implicit_St_times_Q_sparse(input, N, M, chunksize, rowsums, colsums, total, Q)
    B = StQ'

    println("SVD of small matrix: svd(B)")
    W, sigma, Vt = svd(B)
    U_svd = Q * W

    sigma_dim = sigma[1:dim]
    U_dim = U_svd[:, 1:dim]
    V_dim = Vt[:, 1:dim]

    F = zeros(Float64, N, dim)
    G_coord = zeros(Float64, M, dim)
    for k in 1:dim
        for i in 1:N
            F[i, k] = sigma_dim[k] * U_dim[i, k]
        end
        for j in 1:M
            G_coord[j, k] = sigma_dim[k] * V_dim[j, k]
        end
    end

    total_inertia = compute_total_inertia_sparse(input, N, M, rowsums, colsums, total)
    inertia = sigma_dim .^ 2

    return (F, G_coord, sigma_dim, inertia, total_inertia)
end

# Compute total inertia (sparse)
function compute_total_inertia_sparse(input, N, M, rowsums, colsums, total)
    # Total inertia = sum_ij (x_ij - e_ij)^2 / e_ij / n
    # where e_ij = r_i * c_j / n
    # For sparse data: non-zero entries contribute (x_ij - e_ij)^2 / e_ij
    # Zero entries contribute e_ij (since (0 - e_ij)^2 / e_ij = e_ij)
    # Total = [sum over nonzero: (x_ij - e_ij)^2 / e_ij] + [sum over zero: e_ij]
    # = [sum over nonzero: (x_ij - e_ij)^2 / e_ij] + [sum_all e_ij - sum_nonzero e_ij]
    # sum_all e_ij = sum_i r_i * sum_j c_j / n = n^2 / n = n
    # So Total = [sum over nonzero: (x_ij - e_ij)^2 / e_ij - e_ij] + n

    chi2_contribution = 0.0
    sum_expected_nonzero = 0.0
    open(input) do file
        stream = ZstdDecompressorStream(file)
        tmpN = zeros(UInt32, 1)
        tmpM = zeros(UInt32, 1)
        read!(stream, tmpN)
        read!(stream, tmpM)
        buf = zeros(UInt32, 3)
        while !eof(stream)
            read!(stream, buf)
            row, col, val = buf[1], buf[2], buf[3]
            x = Float64(val)
            e = rowsums[row] * colsums[col] / total
            if e > 0
                chi2_contribution += (x - e)^2 / e
                sum_expected_nonzero += e
            end
        end
        close(stream)
    end
    # Zero entries contribute: (sum_all_expected - sum_nonzero_expected)
    # sum_all_expected = total
    total_chi2 = chi2_contribution + (total - sum_expected_nonzero)
    return total_chi2 / total
end
