# Types
struct CA end
struct SPARSE_CA end
struct BINCOO_CA end

# Check NaN value
function checkNaN(X::AbstractArray)
    if any(isnan, X)
        error("NaN values are generated")
    end
end

# Output the result of CA
function output(outdir::AbstractString, out::Tuple)
    write_csv(joinpath(outdir, "Row_coordinates.csv"), out[1])
    write_csv(joinpath(outdir, "Col_coordinates.csv"), out[2])
    write_csv(joinpath(outdir, "Singular_values.csv"), out[3])
    write_csv(joinpath(outdir, "Inertia.csv"), out[4])
    write_csv(joinpath(outdir, "Total_inertia.csv"), out[5])
end

write_csv(filename::AbstractString, data) = writedlm(filename, data, ',')
read_csv(filename::AbstractString) = readdlm(filename, ',')
read_csv(filename::AbstractString, ::Type{T}) where {T} = readdlm(filename, ',', T)

# Return N, M (Zstandard)
function nm(input::AbstractString)
    N = zeros(UInt32, 1)
    M = zeros(UInt32, 1)
    open(input) do file
        stream = ZstdDecompressorStream(file)
        read!(stream, N)
        read!(stream, M)
        close(stream)
    end
    return N[], M[]
end

# Parse command line options
function parse_commandline(camodel::Union{CA,SPARSE_CA,BINCOO_CA})
    s = ArgParseSettings()

    @add_arg_table! s begin
        ("--input", "-i")
        help = "Julia Binary file generated by `OnlinePCA.csv2bin`, `OnlinePCA.mm2bin`, or `OnlineNMF.bincoo2bin` function."
        arg_type = AbstractString
        required = true
        ("--outdir", "-o")
        help = "The directory user want to save the result."
        arg_type = AbstractString
        default = "."
        required = false
        ("--dim", "-d")
        help = "The number of dimensions of CA."
        arg_type = Union{Number,AbstractString}
        default = 3
        "--noversamples"
        help = "The number of over-sampling for randomized SVD."
        arg_type = Union{Number,AbstractString}
        default = 5
        "--niter"
        help = "The number of power iterations for randomized SVD."
        arg_type = Union{Number,AbstractString}
        default = 3
        ("--chunksize", "-c")
        help = "The number of rows reading at once (e.g. 5000)."
        arg_type = Union{Number,AbstractString}
        default = 0
    end

    return parse_args(s)
end
